version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app
  thumbor:
    image: apsl/thumbor:latest
    volumes:
      - data:/data
    ports:
      - '8000:8000'
    environment:
      - DETECTORS=['thumbor.detectors.face_detector','thumbor.detectors.feature_detector']
    networks:
      - app
  minio:
    image: minio/minio
    command: server /data
    volumes:
      - data:/data
    ports:
      - '9000:9000'
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7MINIO
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYMINIO
    networks:
      - app
  mysql:
    image: mysql:8.0.18
    environment:
      MYSQL_DATABASE: media
      MYSQL_USER: AKIAIOSFODNN7MYSQL
      MYSQL_PASSWORD: bPxRfiCYMYSQL
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
volumes:
  data:
    driver: local
networks:
  app:
    driver: bridge